on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: mljmsacr.azurecr.io
        username: ${{ secrets.acr_mljmsacr_username }}
        password: ${{ secrets.acr_mljmsacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/complete" -f  "complete/Dockerfile" -t mljmsacr.azurecr.io/wingtiptoysakscluster:${{ github.sha }}
        docker push mljmsacr.azurecr.io/wingtiptoysakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_wingtiptoysakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep wingtiptoysakscluster7519 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace wingtiptoysakscluster7519`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: wingtiptoysakscluster7519
        container-registry-url: mljmsacr.azurecr.io
        container-registry-username: ${{ secrets.acr_mljmsacr_username }}
        container-registry-password: ${{ secrets.acr_mljmsacr_password }}
        secret-name: wingtiptoysadockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: wingtiptoysakscluster7519
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          mljmsacr.azurecr.io/wingtiptoysakscluster:${{ github.sha }}
        imagepullsecrets: |
          wingtiptoysadockerauth